import { NextResponse } from "next/server";

export const dynamic = "force-dynamic";

const FLEET_IMAGES = [
  "10t-9m-flatbed-tractor-trailer.webp",
  "10t-samag-70-series-crane-truck.webp",
  "10t-tcm-forklift.webp",
  "10t-telehandler-hth10.webp",
  "10t-ubt-drawbar-truck-trailer.webp",
  "110t-mobile-crane-managed-hire.webp",
  "11t-hino-700-crane-truck-8-3t-palfinger.webp",
  "12-5m-trailer-mounted-cherry-picker.webp",
  "2-5t-telehandler-2505.webp",
  "2-tine-ripper.webp",
  "23kva-diesel-generator.webp",
  "26m-cherry-picker.webp",
  "3-5t-telehandler-3512.webp",
  "3-5t-zoomlion-forklift.webp",
  "30kva-diesel-generator.webp",
  "35t-man-33-480-truck-step-deck-trailer.webp",
  "4m-v-tec-trailer.webp",
  "4t-telehandler-4017.webp",
  "500l-diesel-bowser.webp",
  "50kva-diesel-generator.webp",
  "6m-flatbed-trailer.webp",
  "6m-v-tec-trailer.webp",
  "8t-6m-tractor-trailer.webp",
  "9t-telehandler.webp",
  "box-trailers-venter-karet-challenger.webp",
  "cable-trolley.webp",
  "case-cx220c-excavator.webp",
  "case-jx75-tractor.webp",
  "case-skid-steer-loader.webp",
  "case-tlb-backhoe-loader.webp",
  "cat-cranes-logistics.webp",
  "cat-earthmoving.webp",
  "cat-forklifts.webp",
  "cat-hv-diagnostics.webp",
  "cat-personnel.webp",
  "cat-power-site.webp",
  "cat-solar-piling.webp",
  "cat-telehandlers.webp",
  "cat-tractors.webp",
  "cat-trailers.webp",
  "cat-vehicle-hire.webp",
  "cta-fleet.webp",
  "cve-truck-trailer.webp",
  "haulotte-telehandler.webp",
  "hero-home.webp",
  "hino-500-tipper.webp",
  "hva60-vlf-high-voltage-cable-tester.webp",
  "hyundai-h100-dropside.webp",
  "jcb-telehandler.webp",
  "landini-tractor.webp",
  "managed-hire.webp",
  "massey-ferguson-tractor.webp",
  "mercedes-benz-sprinter-23-seater.webp",
  "multione-multiloader.webp",
  "nissan-np200.webp",
  "operators.webp",
  "proj-demolition.webp",
  "proj-steelwork.webp",
  "proj-warehouse.webp",
  "sherla-cable-sheath-fault-locator-010kv.webp",
  "site-containers-office-store-ablution-kitchen.webp",
  "slasher-aem.webp",
  "slasher-dicla.webp",
  "solar-ramming-pile-driver.webp",
  "toyota-hilux-2-4-gd-6-double-cab-with-canopy.webp",
  "toyota-hilux-2-4-gd-6-double-cab.webp",
  "toyota-hilux-2-4-gd-6-extended-cab.webp",
  "toyota-hilux-2-4-gd-6-single-cab-2.webp",
  "toyota-hilux-2-4-gd-6-single-cab-4x4.webp",
  "toyota-hilux-2-4-gd-6-single-cab.webp",
  "toyota-hilux-2-4-gd-single-cab-with-cable-rack.webp",
  "toyota-hilux-2-5-3-0-d-4d-double-cab.webp",
  "toyota-hilux-4-0-v6-double-cab.webp",
  "toyota-hilux-vvti-single-cab-2-0-2-2-2-4-3-0.webp",
  "toyota-quantum-10-seater.webp",
  "toyota-quantum-14-seater.webp",
  "toyota-quantum-hi-ace-16-seater.webp",
  "v-tec-cable-trailer.webp",
  "vw-crafter-23-seater.webp",
  "water-trailer.webp",
  "wulf-mulcher.webp"
];

export async function GET() {
  try {
    const images = FLEET_IMAGES.map((f) => `/media/${f}`);
    return NextResponse.json({ images });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
