"use server";

import { z } from "zod";
import { headers } from "next/headers";
import { supabaseAdmin } from "@/lib/supabase/server";

/**
 * Enquiry submission.
 *
 * Runs server-side with the service role because `enquiries` has no anon
 * policy at all — bots cannot write into a table holding customer contact
 * details. Everything is validated here as well as in the browser; the
 * client is never trusted (plan §7.4).
 */

const Line = z.object({
  equipmentId: z.string().uuid(),
  slug: z.string().max(120),
  title: z.string().min(1).max(200),
  qty: z.number().int().min(1).max(99),
  days: z.number().int().min(1).max(730),
  requiredFrom: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(),
});

const Payload = z.object({
  name: z.string().trim().min(2, "Please give us a name.").max(120),
  company: z.string().trim().max(160).optional().or(z.literal("")),
  email: z.string().trim().email("That email address doesn't look right.").max(160),
  phone: z.string().trim().min(6, "We need a number to call you back on.").max(40),
  deliverySite: z.string().trim().max(200).optional().or(z.literal("")),
  reason: z.string().trim().max(80).optional().or(z.literal("")),
  projectStartDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/).optional().or(z.literal("")),
  notes: z.string().trim().max(4000).optional().or(z.literal("")),
  consent: z.literal(true, {
    errorMap: () => ({ message: "We need your consent to store these details." }),
  }),
  website: z.string().max(0, "Rejected."), // honeypot — real people leave it empty
  items: z.array(Line).min(1, "Your enquiry is empty.").max(60),
});

export type EnquiryResult =
  | { ok: true; reference: string }
  | { ok: false; error: string; field?: string };

/** Crude per-instance rate limit. Backstop only — the honeypot does the real work. */
const seen = new Map<string, number[]>();
const WINDOW_MS = 10 * 60_000;
const MAX_PER_WINDOW = 5;

function rateLimited(ip: string): boolean {
  const now = Date.now();
  const hits = (seen.get(ip) ?? []).filter((t) => now - t < WINDOW_MS);
  hits.push(now);
  seen.set(ip, hits);
  return hits.length > MAX_PER_WINDOW;
}

const _REASONS_UNUSED = [
  "Quotation", "Heavy Machine Rental", "Vehicle Hire", "Truck Hire", "Tractor Hire",
  "Forklift Hire", "Telehandler & Access Hire", "Crane Hire (Managed)",
  "Plant Operator Supply", "Site Establishment (Containers)",
  "HV Cable Testing & Fault Location", "Solar Piling", "Tool Hire",
  "Long-Term / Project Hire", "Cross-Border Hire", "Careers", "General Enquiry",
] as const;

export async function submitEnquiry(raw: unknown): Promise<EnquiryResult> {
  const parsed = Payload.safeParse(raw);
  if (!parsed.success) {
    const first = parsed.error.issues[0];
    return { ok: false, error: first.message, field: String(first.path[0] ?? "") };
  }
  const d = parsed.data;

  const h = await headers();
  const ip = (h.get("x-forwarded-for") ?? "").split(",")[0].trim() || "unknown";
  if (rateLimited(ip)) {
    return { ok: false, error: "Too many enquiries from this connection. Please call us instead." };
  }

  const db = supabaseAdmin();

  // Denormalised table for the notification email body.
  const itemsSummary = d.items
    .map((i) => `${i.qty} × ${i.title} — ${i.days} days${i.requiredFrom ? `, from ${i.requiredFrom}` : ""}`)
    .join("\n");

  // reference is generated by a database default, daily-resetting, in SAST
  const { data: enquiry, error: insErr } = await db
    .from("enquiries")
    .insert({
      name: d.name,
      company: d.company || null,
      email: d.email,
      phone: d.phone,
      delivery_site: d.deliverySite || null,
      reason: d.reason || null,
      project_start_date: d.projectStartDate || null,
      notes: d.notes || null,
      items_summary: itemsSummary,
      consent: true,
      source_ip: ip === "unknown" ? null : ip,
      user_agent: h.get("user-agent")?.slice(0, 500) ?? null,
    })
    .select("id,reference,submitted_at")
    .single();

  if (insErr || !enquiry) {
    console.error("enquiry insert failed:", insErr?.message);
    return { ok: false, error: "We couldn't save that. Please phone us on +27 66 429 5788." };
  }

  const { error: itemsErr } = await db.from("enquiry_items").insert(
    d.items.map((i) => ({
      enquiry_id: enquiry.id,
      equipment_id: i.equipmentId,
      item_title: i.title,
      quantity: i.qty,
      days: i.days,
      required_from: i.requiredFrom,
    }))
  );
  if (itemsErr) console.error("enquiry_items insert failed:", itemsErr.message);

  // Email is best-effort: the enquiry is already saved, so a mail failure
  // must never lose the lead or show the customer an error.
  try {
    await sendNotifications(d, enquiry.reference, enquiry.submitted_at);
  } catch (e) {
    console.error("enquiry email failed:", e);
  }

  return { ok: true, reference: enquiry.reference };
}

async function settings(): Promise<Record<string, string>> {
  const { data } = await supabaseAdmin().from("settings").select("key,value");
  return Object.fromEntries((data ?? []).map((r) => [r.key, r.value ?? ""]));
}

async function sendNotifications(
  d: z.infer<typeof Payload>,
  reference: string,
  submittedAt: string
) {
  const key = process.env.RESEND_API_KEY;
  if (!key) {
    console.warn(`RESEND_API_KEY not set — ${reference} saved but no email sent.`);
    return;
  }
  const { Resend } = await import("resend");
  const resend = new Resend(key);
  const s = await settings();

  const from = s["enquiry.from_address"] || "enquiries@mail.ecrentals.co.za";
  const replyTo = s["enquiry.reply_to"] || "info@ecrentals.co.za";
  // Both addresses, as requested — sales and info together on every enquiry.
  const to = [s["enquiry.notify_to"] || "info@ecrentals.co.za",
              s["enquiry.notify_cc"] || "sales@ecrentals.co.za"].filter(Boolean);

  const when = new Intl.DateTimeFormat("en-ZA", {
    dateStyle: "medium", timeStyle: "short", timeZone: "Africa/Johannesburg",
  }).format(new Date(submittedAt));

  const rows = d.items
    .map(
      (i) => `<tr>
        <td style="padding:9px 12px;border-bottom:1px solid #E8E9EB">${esc(i.title)}</td>
        <td style="padding:9px 12px;border-bottom:1px solid #E8E9EB;text-align:right">${i.qty}</td>
        <td style="padding:9px 12px;border-bottom:1px solid #E8E9EB;text-align:right">${i.days}</td>
        <td style="padding:9px 12px;border-bottom:1px solid #E8E9EB">${i.requiredFrom ?? "—"}</td>
      </tr>`
    )
    .join("");

  const internal = `
  <div style="font-family:Inter,Arial,sans-serif;color:#1C1E21;max-width:680px">
    <div style="background:#0A0A0B;padding:20px 24px">
      <span style="color:#fff;font-weight:800;letter-spacing:-.02em;font-size:18px">EC</span>
      <span style="color:#BA1B20;font-weight:800;font-size:18px"> RENTALS</span>
      <div style="color:#F5A524;font-size:11px;letter-spacing:.14em;margin-top:6px">NEW HIRE ENQUIRY</div>
    </div>
    <div style="padding:24px">
      <table style="font-size:14px;margin-bottom:20px">
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">REFERENCE</td><td><b>${esc(reference)}</b></td></tr>
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">SUBMITTED</td><td>${esc(when)} SAST</td></tr>
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">REASON</td><td>${esc(d.reason || "Quotation")}</td></tr>
      </table>

      <h3 style="font-size:12px;letter-spacing:.14em;color:#6B7280;margin:0 0 8px">EQUIPMENT REQUESTED</h3>
      <table style="width:100%;border-collapse:collapse;font-size:14px;margin-bottom:24px">
        <thead><tr style="background:#F5F6F7">
          <th style="padding:9px 12px;text-align:left">Item</th>
          <th style="padding:9px 12px;text-align:right">Qty</th>
          <th style="padding:9px 12px;text-align:right">Days</th>
          <th style="padding:9px 12px;text-align:left">Required from</th>
        </tr></thead>
        <tbody>${rows}</tbody>
      </table>

      <h3 style="font-size:12px;letter-spacing:.14em;color:#6B7280;margin:0 0 8px">CONTACT</h3>
      <table style="font-size:14px;margin-bottom:20px">
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">Name</td><td>${esc(d.name)}</td></tr>
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">Company</td><td>${esc(d.company || "—")}</td></tr>
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">Email</td><td><a href="mailto:${esc(d.email)}">${esc(d.email)}</a></td></tr>
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">Phone</td><td><a href="tel:${esc(d.phone)}">${esc(d.phone)}</a></td></tr>
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">Delivery site</td><td>${esc(d.deliverySite || "—")}</td></tr>
        <tr><td style="padding:3px 16px 3px 0;color:#6B7280">Project start</td><td>${esc(d.projectStartDate || "—")}</td></tr>
      </table>
      ${d.notes ? `<h3 style="font-size:12px;letter-spacing:.14em;color:#6B7280;margin:0 0 8px">NOTES</h3>
        <p style="font-size:14px;white-space:pre-wrap;margin:0">${esc(d.notes)}</p>` : ""}
    </div>
  </div>`;

  await resend.emails.send({
    from: `EC Rentals Enquiries <${from}>`,
    to,
    replyTo: d.email, // replying goes straight back to the customer
    subject: `New Hire Enquiry — ${reference} — ${d.company || d.name}`,
    html: internal,
  });

  const ack = `
  <div style="font-family:Inter,Arial,sans-serif;color:#1C1E21;max-width:600px">
    <div style="background:#0A0A0B;padding:20px 24px">
      <span style="color:#fff;font-weight:800;font-size:18px">EC</span><span style="color:#BA1B20;font-weight:800;font-size:18px"> RENTALS</span>
    </div>
    <div style="padding:24px;font-size:15px;line-height:1.6">
      <p>Thanks ${esc(d.name.split(" ")[0])} — we have your enquiry.</p>
      <p>Your reference is <b>${esc(reference)}</b>. Quote it if you call us.</p>
      <p>We come back on enquiries within <b>24 hours</b>. Availability is confirmed on quotation.</p>
      <table style="font-size:14px;margin:18px 0;border-collapse:collapse;width:100%">
        <thead><tr style="background:#F5F6F7">
          <th style="padding:8px 12px;text-align:left">Item</th>
          <th style="padding:8px 12px;text-align:right">Qty</th>
          <th style="padding:8px 12px;text-align:right">Days</th>
        </tr></thead>
        <tbody>${d.items.map((i) => `<tr>
          <td style="padding:8px 12px;border-bottom:1px solid #E8E9EB">${esc(i.title)}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #E8E9EB;text-align:right">${i.qty}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #E8E9EB;text-align:right">${i.days}</td>
        </tr>`).join("")}</tbody>
      </table>
      <p style="color:#6B7280;font-size:13px">
        EC Rentals (Pty) Ltd · Lead EPC Building, Cnr Hertz &amp; Becquerel Street, Vanderbijlpark<br>
        +27 66 429 5788 · +27 82 850 4902
      </p>
    </div>
  </div>`;

  await resend.emails.send({
    from: `EC Rentals <${from}>`,
    to: [d.email],
    replyTo,
    subject: `We have your enquiry — ${reference}`,
    html: ack,
  });
}

function esc(s: string): string {
  return s.replace(/[&<>"']/g, (c) =>
    ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!
  );
}

